#!/bin/sh

APPDIR=$(dirname "$0")
java -Xms64m -Xmx4000m -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/controlP5.jar:$APPDIR/lib/core.jar:$APPDIR/lib/gluegen-rt-natives-windows-amd64.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-windows-amd64.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/jssc.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/GRemote.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar:$APPDIR/lib/jssc.jar:$APPDIR/lib/serial.jar" GRemote "$@"
